In [1]:
%config Completer.use_jedi = False

In [93]:
import pandas as pd
file = './kaggle_titanic/train.csv'

In [94]:
import numpy as np

In [95]:
data=pd.read_csv(file)

In [96]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# String data convert to numbers

To convert data to numbers, there are 3 ways that I used  
First, get list and create new column using list  
Second, use map function with dic  
Last, mix both of them

In [97]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [98]:
data_name=data['Name']

In [99]:
data_name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

titles and first name convert to numbers


In [100]:
first_name_list = []
last_name_list = []
title_list = []
name_list = []
for i in data_name:
    first_name, name = i.split(',')
    first_name_list.append(first_name)
    #print(name)
    name=name.split(' ')
    
    title_list.append(name[1])
    last_name_list.append(name[2:])
for i in last_name_list:
    for j in i:
        a = ' '.join(i)
    name_list.append(a)

In [101]:
data['first_name']=first_name_list
data['title'] = title_list

In [102]:
data.title.unique()

array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Don.', 'Rev.', 'Dr.', 'Mme.',
       'Ms.', 'Major.', 'Lady.', 'Sir.', 'Mlle.', 'Col.', 'Capt.', 'the',
       'Jonkheer.'], dtype=object)

In [103]:
title_dic = {}
first_name_dic = {}
#print(title_dic.keys())
number = 0
for i in data.title.unique():
    if i not in title_dic.keys():
        title_dic[i] = number
        number+=1
number = 0
for i in data.first_name.unique():
    if i not in first_name_dic.keys():
        first_name_dic[i] = number
        number+=1

In [104]:
first_name_number = []
title_name_number = []
for i in data['first_name']:
    first_name_number.append(first_name_dic[i])
for i in data['title']:
    title_name_number.append(title_dic[i])
    

In [105]:
data['first_name'] = first_name_number
data['title'] = title_name_number

sex convert to numbers

In [106]:
sex_map = {'male' : 0, 'female' : 1}
data['Sex'] = data['Sex'].map(lambda x : sex_map.get(x))

Cabin convert to numbers

In [107]:
data['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [108]:
cabin_dic = {}
number = 1
for i in data['Cabin'].unique():
    if type(i) == float:
        pass
    else:
        j = i[0]
        if j not in cabin_dic.keys():
            cabin_dic[j] = number
            number+=1
            
cabin_list = []
for i in data['Cabin']:
    if type(i) == float:
        cabin_list.append(0)
    else:
        cabin_list.append(cabin_dic[i[0]])

data['Cabin_number'] = cabin_list

# Replace deleted value to estimated value

In [109]:
data['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [110]:
data.groupby(['Embarked','Pclass']).mean()['Fare']

Embarked  Pclass
C         1         104.718529
          2          25.358335
          3          11.214083
Q         1          90.000000
          2          12.350000
          3          11.183393
S         1          70.364862
          2          20.327439
          3          14.644083
Name: Fare, dtype: float64

In [111]:
data[data['Embarked'].isnull()]

PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

     Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked  first_name  title  \
61     1  38.0      0      0  113572  80.0   B28      NaN          59      2   
829    1  62.0      0      0  113572  80.0   B28      NaN         629      1   

     Cabin_number  
61              6  
829             6

# Delete some data

In [112]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  first_name  title  Cabin_number  
0         A/5 21171   7.2500   NaN        S           0      0             0  
1          PC 17599  71.2833   C85        C           1      1             1  
2  STON/O2. 3101282   7.9250   NaN        S           2      2             0  
3            113803  53.1000  C123        S           3      1             1  
4            373450   8.0500   NaN        S           4      0             0

In [113]:
survived = data['Survived']
data.pop('Ticket')
data.pop('Cabin')
data.pop('Age')
data.pop('Survived')
data.pop('Name')
data.pop('PassengerId')
data.pop('Embarked')
data.head()

Pclass  Sex  SibSp  Parch     Fare  first_name  title  Cabin_number
0       3    0      1      0   7.2500           0      0             0
1       1    1      1      0  71.2833           1      1             1
2       3    1      0      0   7.9250           2      2             0
3       1    1      1      0  53.1000           3      1             1
4       3    0      0      0   8.0500           4      0             0

# Split data to train and val

In [114]:
val_rate = 0.2

train_rate=int(891 * 0.2)

In [115]:
data_val = data[:train_rate]
data_train = data[train_rate:]
survived_train = survived[train_rate:]
survived_val = survived[:train_rate]

In [116]:
data_val

Pclass  Sex  SibSp  Parch     Fare  first_name  title  Cabin_number
0         3    0      1      0   7.2500           0      0             0
1         1    1      1      0  71.2833           1      1             1
2         3    1      0      0   7.9250           2      2             0
3         1    1      1      0  53.1000           3      1             1
4         3    0      0      0   8.0500           4      0             0
..      ...  ...    ...    ...      ...         ...    ...           ...
173       3    0      0      0   7.9250         154      0             0
174       1    0      0      0  30.6958         155      0             5
175       3    0      1      1   7.8542         156      0             0
176       3    0      3      1  25.4667         157      3             0
177       1    1      0      0  28.7125         158      2             1

[178 rows x 8 columns]

# Modeling and Learning  
To learn, convert to data into array form


In [117]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [118]:
x_train = data_train.to_numpy()
y_train = survived_train.to_numpy()

x_val = data_val.to_numpy()
y_val = survived_val.to_numpy()

numpy array to tensor

In [119]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)
x_val = torch.FloatTensor(x_val)
y_val = torch.FloatTensor(y_val)

In [120]:
a = torch.tensor([0,2])
b = torch.tensor([1,1])
torch.cat((a,b), dim = 0)

tensor([0, 2, 1, 1])

In [121]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(8,64)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(64,32)
        self.fc3= nn.Linear(32,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        
        return x

# Tuning hyperparameters using validation

In [122]:
net = Net()
optimizer = optim.Adam(lr=0.001,params= net.parameters())

In [92]:
x_train

tensor([[  2.,   0.,  30.,  ..., 159.,   0.,   0.],
        [  3.,   0.,  36.,  ..., 160.,   0.,   0.],
        [  3.,   1.,  nan,  ..., 144.,   2.,   0.],
        ...,
        [  3.,   1.,  nan,  ..., 604.,   2.,   0.],
        [  1.,   0.,  26.,  ..., 665.,   0.,   1.],
        [  3.,   0.,  32.,  ..., 666.,   0.,   0.]])

# Accuracy and test

I think it is too small to get good enough result due to tiny dataset.  
So I decide not to split train and valid set

In [123]:
x_set = torch.cat((x_train, x_val),dim = 0)
y_set = torch.cat((y_train, y_val),dim = 0)

In [124]:
net = Net()
optimizer = optim.Adam(lr=0.0005,params= net.parameters())

In [125]:
epochs = 200

for epoch in range(epochs):
    running_loss = 0.0
    running_val_loss = 0.0
    accuracy = 0.0
    running_loss = 0.0
    for i, (x,y) in enumerate(zip(x_set,y_set)):
        
        y = torch.tensor([y])
        optimizer.zero_grad()
        outputs = net(x)

        loss = F.binary_cross_entropy(outputs,y)
        loss.backward()
        optimizer.step()
        running_loss+=loss.item()
        y_hat = outputs[0]
        if y_hat>0.5:
            y_hat = 1
        else:
            y_hat = 0
        #print(y_train.shape)
        if y_hat == y[0]:
            accuracy+=1
    print("[{:2d},{:2d}] accuracy : {:.3f}, loss : {:.3f}".format(epoch,epochs,accuracy/len(x_set),running_loss))
    

[ 0,200] accuracy : 0.586, loss : 740.125
[ 1,200] accuracy : 0.633, loss : 649.796
[ 2,200] accuracy : 0.658, loss : 607.024
[ 3,200] accuracy : 0.679, loss : 585.219
[ 4,200] accuracy : 0.701, loss : 563.586
[ 5,200] accuracy : 0.716, loss : 544.299
[ 6,200] accuracy : 0.730, loss : 534.833
[ 7,200] accuracy : 0.734, loss : 518.034
[ 8,200] accuracy : 0.743, loss : 504.556
[ 9,200] accuracy : 0.738, loss : 511.006
[10,200] accuracy : 0.753, loss : 482.599
[11,200] accuracy : 0.762, loss : 478.219
[12,200] accuracy : 0.762, loss : 472.253
[13,200] accuracy : 0.764, loss : 467.937
[14,200] accuracy : 0.768, loss : 463.677
[15,200] accuracy : 0.771, loss : 456.570
[16,200] accuracy : 0.762, loss : 448.763
[17,200] accuracy : 0.774, loss : 440.334
[18,200] accuracy : 0.780, loss : 437.298
[19,200] accuracy : 0.774, loss : 440.449
[20,200] accuracy : 0.780, loss : 430.957
[21,200] accuracy : 0.783, loss : 432.587
[22,200] accuracy : 0.782, loss : 430.424
[23,200] accuracy : 0.787, loss : 

[193,200] accuracy : 0.851, loss : 303.513
[194,200] accuracy : 0.854, loss : 307.911
[195,200] accuracy : 0.850, loss : 309.687
[196,200] accuracy : 0.850, loss : 308.383
[197,200] accuracy : 0.850, loss : 305.172
[198,200] accuracy : 0.847, loss : 308.820
[199,200] accuracy : 0.845, loss : 307.691


Delete first name

In [127]:
test_file = './kaggle_titanic/test.csv'
test_data = pd.read_csv(test_file)
#test_data = test_data.to_numpy()
#test_data = torch.FloatTensor(test_data)

In [128]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

To submit, set index to passengerID

In [129]:
test_data.set_index('PassengerId')
test_index = test_data.index

In [130]:
test_name=test_data['Name']
first_name_list = []
last_name_list = []
title_list = []
name_list = []
for i in test_name:
    first_name, name = i.split(',')
    first_name_list.append(first_name)
    #print(name)
    name=name.split(' ')
    
    title_list.append(name[1])
    last_name_list.append(name[2:])
for i in last_name_list:
    for j in i:
        a = ' '.join(i)
    name_list.append(a)

test_data['first_name']=first_name_list
test_data['title'] = title_list

title_dic = {}
first_name_dic = {}
#print(title_dic.keys())
number = 0
for i in test_data.title.unique():
    if i not in title_dic.keys():
        title_dic[i] = number
        number+=1
number = 0
for i in test_data.first_name.unique():
    if i not in first_name_dic.keys():
        first_name_dic[i] = number
        number+=1

first_name_number = []
title_name_number = []
for i in test_data['first_name']:
    first_name_number.append(first_name_dic[i])
for i in test_data['title']:
    title_name_number.append(title_dic[i])
    
test_data['first_name'] = first_name_number
test_data['title'] = title_name_number


sex_map = {'male' : 0, 'female' : 1}
test_data['Sex'] = test_data['Sex'].map(lambda x : sex_map.get(x))
test_data.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    0   
3          895       3                              Wirz, Mr. Albert    0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  first_name  title  
0  34.5      0      0   330911   7.8292   NaN        Q           0      0  
1  47.0      1      0   363272   7.0000   NaN        S           1      1  
2  62.0      0      0   240276   9.6875   NaN        Q           2      0  
3  27.0      0      0   315154   8.6625   NaN        S           3      0  
4  22.0      1      1  3101298  12.2875   NaN        S           4      1

# Same way to test dataset

In [131]:
cabin_dic = {}
number = 1
for i in test_data['Cabin'].unique():
    if type(i) == float:
        pass
    else:
        j = i[0]
        if j not in cabin_dic.keys():
            cabin_dic[j] = number
            number+=1
            
cabin_list = []
for i in test_data['Cabin']:
    if type(i) == float:
        cabin_list.append(0)
    else:
        cabin_list.append(cabin_dic[i[0]])

test_data.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    0   
3          895       3                              Wirz, Mr. Albert    0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  first_name  title  
0  34.5      0      0   330911   7.8292   NaN        Q           0      0  
1  47.0      1      0   363272   7.0000   NaN        S           1      1  
2  62.0      0      0   240276   9.6875   NaN        Q           2      0  
3  27.0      0      0   315154   8.6625   NaN        S           3      0  
4  22.0      1      1  3101298  12.2875   NaN        S           4      1

In [132]:
test_data['Cabin_number'] = cabin_list
test_data.pop('Ticket')
test_data.pop('Cabin')
test_data.pop('Name')
test_data.pop('PassengerId')
test_data.pop('Embarked')
test_data.pop('Age')


NameError: name 'test_dat' is not defined

In [134]:
test_data.head()

Pclass  Sex  SibSp  Parch     Fare  first_name  title  Cabin_number
0       3    0      0      0   7.8292           0      0             0
1       3    1      1      0   7.0000           1      1             0
2       2    0      0      0   9.6875           2      0             0
3       3    0      0      0   8.6625           3      0             0
4       3    1      1      1  12.2875           4      1             0

In [142]:
test_data_arr = test_data.to_numpy()
test_data_torch = torch.FloatTensor(test_data_arr)
final_outputs = []
for i in test_data_torch:
    outputs  = net(i)
    y_hat = outputs[0]
    if y_hat>0.5:
        y_hat = 1
    else:
        y_hat = 0
    final_outputs.append(y_hat)

In [138]:
test_index=test_index.values+892

In [146]:
final_outputs = np.array(final_outputs)

In [147]:
final_outputs

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [150]:
result = np.concatenate((test_index.reshape(-1,1),final_outputs.reshape(-1,1)),axis = 1)
result[:5]

array([[892,   0],
       [893,   1],
       [894,   0],
       [895,   0],
       [896,   0]], dtype=int64)

In [151]:
submission = pd.DataFrame(result, columns=["PassengerId","Survived"])
submission.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         0

In [152]:
submission.to_csv("my_submission.csv", index = False)